// src/InertiaNet.Templates/templates/vue-starter/ClientApp/src/pages/Home.vue
<script setup lang="ts">
const title = 'InertiaNet Vue Starter'
</script>

<template>
  <main style="font-family: Inter, system-ui, sans-serif; padding: 3rem; max-width: 720px; margin: 0 auto;">
    <h1>{{ title }}</h1>
    <p>Your ASP.NET Core + InertiaNet + Vue starter is ready.</p>
  </main>
</template>

// src/InertiaNet.Templates/templates/react-starter/ClientApp/src/pages/Home.tsx
type HomeProps = {
  title?: string
}

export default function Home({ title = 'InertiaNet React Starter' }: HomeProps) {
  return (
    <main style={{ fontFamily: 'Inter, system-ui, sans-serif', padding: '3rem', maxWidth: 720, margin: '0 auto' }}>
      <h1>{title}</h1>
      <p>Your ASP.NET Core + InertiaNet + React starter is ready.</p>
    </main>
  )
}
